root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/todotracker ."
bin = "./tmp/todotracker"
full_bin = ""
delay = 500
exclude_dir = ["tmp", "bin", "node_modules"]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
include_ext = ["go", "html", "css", "js"]
send_interrupt = true
kill_delay = 500

[log]
time = true
main_only = false
